<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <!-- RESX ресурсы для варианта локализации через ResourceManager -->
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings.en-US.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.en-US.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExternalLocalization\ExternalLocalization.csproj" />
  </ItemGroup>

  <!-- В этой ветке (внешняя библиотека) XAML словари исключены из компиляции -->
  <ItemGroup>
    <Page Remove="Resources\Strings.ru-RU.xaml" />
    <Page Remove="Resources\Strings.en-US.xaml" />
  </ItemGroup>

</Project>
