//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFunc.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfFunc.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛР1 - Панов Артем (локализация).
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        internal static string Default_Button_Update {
            get {
                return ResourceManager.GetString("Default.Button.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямая привязка vs через ViewModel.
        /// </summary>
        internal static string Default_Group_DirectVsVm {
            get {
                return ResourceManager.GetString("Default.Group.DirectVsVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox (TwoWay по умолчанию).
        /// </summary>
        internal static string Default_Group_TextBox {
            get {
                return ResourceManager.GetString("Default.Group.TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBlock (OneWay по умолчанию).
        /// </summary>
        internal static string Default_Group_Time {
            get {
                return ResourceManager.GetString("Default.Group.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения в TextBox сразу обновляют TextBlock.
        /// </summary>
        internal static string Default_Hint_Sync {
            get {
                return ResourceManager.GetString("Default.Hint.Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямая привязка элементов:.
        /// </summary>
        internal static string Default_Text_DirectBinding {
            get {
                return ResourceManager.GetString("Default.Text.DirectBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка через ViewModel:.
        /// </summary>
        internal static string Default_Text_VmBinding {
            get {
                return ResourceManager.GetString("Default.Text.VmBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Привязка по умолчанию.
        /// </summary>
        internal static string Default_Title {
            get {
                return ResourceManager.GetString("Default.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык интерфейса:.
        /// </summary>
        internal static string Language_Caption {
            get {
                return ResourceManager.GetString("Language.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language.Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Message_Caption {
            get {
                return ResourceManager.GetString("Message.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен элемент списка.
        /// </summary>
        internal static string Message_ItemAdded {
            get {
                return ResourceManager.GetString("Message.ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию.
        /// </summary>
        internal static string Tab_DefaultBinding {
            get {
                return ResourceManager.GetString("Tab.DefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string Tab_OneTimeBinding {
            get {
                return ResourceManager.GetString("Tab.OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонняя привязка.
        /// </summary>
        internal static string Tab_OneWayBinding {
            get {
                return ResourceManager.GetString("Tab.OneWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        internal static string Tab_Triggers {
            get {
                return ResourceManager.GetString("Tab.Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка.
        /// </summary>
        internal static string Tab_TwoWayBinding {
            get {
                return ResourceManager.GetString("Tab.TwoWayBinding", resourceCulture);
            }
        }
    }
}
